### ISSUE TITLE
depmap licence

### ISSUE THREAD

**Issue by lgatto** [UCLouvain-CBIO/depmap#15]
- I saw that you choose GPL-2 | GPL-3 for a licence? Any reason why both?
- Is there a specific license for the data? Does the depmap data portal say anything?

**Comment by tfkillian** [comment]
It doesn't say anywhere on the site, so I've contacted the Broad Institute directly about the matter.

**Comment by lgatto** [comment]
Ok, thanks.

So I think we will probably need 2 licences. One for the package, in the DESCRIPTION file, and then also provide one for the data (hoping that they explicitly allow us to redistribute their data).
