### ISSUE TITLE
Error installing depmap

### ISSUE THREAD

**Issue by MatDal** [UCLouvain-CBIO/depmap#35]
Hello,

I have an error trying to install depmap:

Error: package or namespace load failed for ‘depmap’:
 .onLoad failed in loadNamespace() for 'depmap', details:
  call: FUN(X[[i]], ...)
  error: ‘rnai_19Q2’ not found in ExperimentHub
Error: loading failed
Execution halted

Thanks
Best
M

**Comment by lgatto** [comment]
Sorry about that - a PR was merged when it shouldn't have. You should be able to install a working version with 
```r
remotes::install_github("UCLouvain-CBIO/depmap", ref = "4a9f52ed6cf9c3821891ebdd9db317194d6518c9")
```
Thank you for your interest.

**Comment by MatDal** [comment]
now it works,
thanks for the nice and useful tool!!

M
