### ISSUE TITLE
Ensembl_id

### ISSUE THREAD

**Issue by aloriot** [UCLouvain-CBIO/depmap#36]
It would be great to include in rnai and the crispy datasets a column with gene Ensembl identifiers, in order to be able to merge in a straightforward manner these datasets with the tpm dataset (where genes are identified by Ensembl_ids)

**Comment by lgatto** [comment]
Good suggestion, thanks. 

@tfkillian - this would also be useful as part of the coming new version.

**Comment by tfkillian** [comment]
This bug has been fixed in the 19_Q2 branch
