### ISSUE TITLE
character-type column for entrez_id

### ISSUE THREAD

**Issue by aloriot** [UCLouvain-CBIO/depmap#37]
In rnai and crispr datasets, entrez_id should be columns of integer instead of character (this is a source of bug if we want to merge these datasets -by entrez id- with our own genes dataset)

**Comment by lgatto** [comment]
@tfkillian - could you do this change as part of the new version that will include 19_Q2.

**Comment by tfkillian** [comment]
Good catch. I will work it into the next update this week.

**Comment by lgatto** [comment]
@tfkillian - has this been fixed? If so, could you close the issue.

**Comment by tfkillian** [comment]
Yes, this has been fixed for all datasets.
