### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by ndjayne** [UCLouvain-CBIO/depmap#41]
So I installed ~2 days ago, no major issues. However, today, while helping a colleague I got this error then got it myself trying the same install:

Error: Failed to install 'depmap' from GitHub:
  (converted from warning) installation of package ‘C:/Users/__username__/AppData/Local/Temp/Rtmp4uHAOP/file2b249ff41c2/depmap_0.99.5.tar.gz’ had non-zero exit status

**Comment by lgatto** [comment]
I suspect that's because yesterday we pushed a update with the 19_Q3 data. You will need the development version of Bioconductor to use that.

**Comment by lgatto** [comment]
Also, to be able to help, developers need the actual error message and the output of `sessionInfo()`.

**Comment by ndjayne** [comment]
![image](https://user-images.githubusercontent.com/33524947/63110346-0db09800-bf40-11e9-8a9e-b2021f9907b2.png)

**Comment by lgatto** [comment]
No, that only tells that installation failed, but not why it fails. Here is the kind of output we need.

Here is an example output that tells us that the installation fails because data 19_Q2 is missing, which is the result of this computer running the release version of Bioconductor (i.e 3.9).

```
> BiocManager::install("UCLouvain-CBIO/depmap")
Bioconductor version 3.9 (BiocManager 1.30.4), R 3.6.0 RC (2019-04-21 r76417)
Installing github package(s) 'UCLouvain-CBIO/depmap'
Downloading GitHub repo UCLouvain-CBIO/depmap@master
✔  checking for file ‘/tmp/RtmpkAfKvU/remotes27e27a28b491/UCLouvain-CBIO-depmap-9492961/DESCRIPTION’
─  preparing ‘depmap’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘depmap_0.99.5.tar.gz’
   
* installing *source* package ‘depmap’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Using temporary cache /tmp/RtmpntHGKv/BiocFileCache
snapshotDate(): 2019-04-29
Using temporary cache /tmp/RtmpntHGKv/BiocFileCache
Using temporary cache /tmp/RtmpntHGKv/BiocFileCache
Using temporary cache /tmp/RtmpntHGKv/BiocFileCache
snapshotDate(): 2019-04-29
Using temporary cache /tmp/RtmpntHGKv/BiocFileCache
Using temporary cache /tmp/RtmpntHGKv/BiocFileCache
Error: package or namespace load failed for ‘depmap’:
 .onLoad failed in loadNamespace() for 'depmap', details:
  call: FUN(X[[i]], ...)
  error: ‘rnai_19Q2’ not found in ExperimentHub
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/lgatto/R/x86_64-pc-linux-gnu-library/3.6/depmap’
Error: Failed to install 'depmap' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpkAfKvU/file27e241230b88/depmap_0.99.5.tar.gz’ had non-zero exit status
> sessionInfo()
R version 3.6.0 RC (2019-04-21 r76417)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/libf77blas.so.3.10.3
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] ps_1.3.0           prettyunits_1.0.2  withr_2.1.2        crayon_1.3.4      
 [5] rprojroot_1.3-2    assertthat_0.2.1   R6_2.4.0           backports_1.1.4   
 [9] magrittr_1.5       cli_1.1.0          curl_4.0           remotes_2.1.0     
[13] callr_3.3.1        tools_3.6.0        compiler_3.6.0     processx_3.4.1    
[17] pkgbuild_1.0.3     BiocManager_1.30.4
> BiocManager::version()
[1] ‘3.9’
```

**Comment by lgatto** [comment]
To learn about Bioconductor devel, see http://bioconductor.org/developers/how-to/useDevel/.

**Comment by ndjayne** [comment]
Sorry, I am new to this sort of stuff. I got the devel version and got this error afterward:

BiocManager::install("uclouvain-cbio/depmap")
Bioconductor version 3.10 (BiocManager 1.30.4), R 3.6.1 (2019-07-05)
Installing github package(s) 'uclouvain-cbio/depmap'
Downloading GitHub repo uclouvain-cbio/depmap@master
These packages have more recent versions available.
Which would you like to update?

1: All                               
2: CRAN packages only                
3: None                              
4: Biobase (2.44.0 -> 2.45.0 ) [CRAN]
5: IRanges (2.18.1 -> 2.19.10) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
1
S4Vectors (NA     -> 0.23.17) [CRAN]
Biobase   (2.44.0 -> 2.45.0 ) [CRAN]
IRanges   (2.18.1 -> 2.19.10) [CRAN]
Installing 3 packages: S4Vectors, Biobase, IRanges
Installing packages into ‘C:/Users/Nathan/Documents/Programs/R_lib’
(as ‘lib’ is unspecified)
trying URL 'https://bioconductor.org/packages/3.10/bioc/bin/windows/contrib/3.6/S4Vectors_0.23.17.zip'
Content type 'application/zip' length 2117901 bytes (2.0 MB)
downloaded 2.0 MB

trying URL 'https://bioconductor.org/packages/3.10/bioc/bin/windows/contrib/3.6/Biobase_2.45.0.zip'
Content type 'application/zip' length 2422505 bytes (2.3 MB)
downloaded 2.3 MB

trying URL 'https://bioconductor.org/packages/3.10/bioc/bin/windows/contrib/3.6/IRanges_2.19.10.zip'
Content type 'application/zip' length 2358995 bytes (2.2 MB)
downloaded 2.2 MB

package ‘S4Vectors’ successfully unpacked and MD5 sums checked
Error: Failed to install 'depmap' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘S4Vectors’

**Comment by ndjayne** [comment]
sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dbplyr_1.4.2

loaded via a namespace (and not attached):
Error in x[["Version"]] : subscript out of bounds
In addition: Warning message:
In FUN(X[[i]], ...) :
  DESCRIPTION file of package 'S4Vectors' is missing or broken

**Comment by ndjayne** [comment]
After fixing that package issue I successfully installed and loaded depmap, thank you.

**Comment by lgatto** [comment]
Excellent!
