### ISSUE TITLE
Loading data using named functions

### ISSUE THREAD

**Issue by lgatto** [UCLouvain-CBIO/depmap#42]
I can't remember if there are named functions to lead data - something like 
```
rnai <- depmap_rnai()
```
that would automatically load the latest RNAi data from ExperimentHub.

**Comment by tfkillian** [comment]
no such functions like that currently exist. I will go about creating them and report back in this issue when they are finished.

**Comment by tfkillian** [comment]
these functions have been created on branch 19_Q3 and added with the latest pull request. if they are satisfactory, we can close this issue

**Comment by lgatto** [comment]
Thanks. I'm checking the package at the moment.

Another change that you need to do every time you intend to push to Bioconductor is the version number. It is essential that the version number of bumped (i.e. higher than what is currently available on the Bioconductor git server), otherwise the new package will never be released. See http://bioconductor.org/developers/how-to/version-numbering/ for details.

In this case, both github and Bioc version are 0.99.5, and we need to bump to 0.99.6 on github.
