### ISSUE TITLE
20Q3

### ISSUE THREAD

**Issue by mjsteinbaugh** [UCLouvain-CBIO/depmap#57]
Hi, I'm trying out the depmap package and really like the integration with ExperimentHub. One issue is that the stable version of the package is currently two releases (20Q1) behind the latest quarterly release available on the DepMap website (20Q3). Is there a mechanism to push 20Q3 to ExperimentHub and then query using the depmap package?

**Comment by lgatto** [comment]
Hi - thank you for your interest. 

Unfortunately, the only way to access the development version of `depmap` and `ExperimentHub` is to use the [development version](http://bioconductor.org/developers/how-to/useDevel/) of Bioconductor.

**Comment by mjsteinbaugh** [comment]
OK thanks @lgatto
