### ISSUE TITLE
depmap_mutationCalls() returning metadata table

### ISSUE THREAD

**Issue by imkeller** [UCLouvain-CBIO/depmap#64]
I am using the Bioconductor depmap package and I find it very useful and easy to use.

It seems like the `depmap_mutationCalls()` function is returning the metadata table.
`mutationCalls_19Q3()` returns the correct mutation data.
Could you take a look at it?

**Comment by imkeller** [comment]
Also, the `ensembl_id` in the table returned by `depmap_TPM()` looks like an entrez ID.

**Comment by lgatto** [comment]
Thank you for the issue, Katharina. Regarding 

> It seems like the `depmap_mutationCalls()` function is returning the metadata table. `mutationCalls_19Q3()` returns the correct mutation data.

there was indeed a bug where the copy numbers were returned instead of mutation calls, which should be fixed in GitHub, and soon on Bioconductor.

And indeed, the id isn't ensembl, but suspiciously looks like an entrez id. Will be fixed too.

**Comment by lgatto** [comment]
@tfkillian - I have fixed this in the script that generates the data. Could you update the data and update it on ExperimentHub, please.

**Comment by lgatto** [comment]
Pushed to Bioc, but waiting that the actual data is updated before closing the issue.

**Comment by lgatto** [comment]
> @tfkillian - I have fixed this in the script that generates the data. Could you update the data and update it on ExperimentHub, please.

Has this been done? New release is planned today!

**Comment by tfkillian** [comment]
@lgatto This update will be pushed with the next data release.

**Comment by tfkillian** [comment]
All TPM datasets with Entrez ID have been updated and now are available on EH. @lgatto you can close this issue
