### ISSUE TITLE
definition of "co-dependent genes"

### ISSUE THREAD

**Issue by Shicheng-Guo** [UCLouvain-CBIO/depmap#67]
I am wondering whether expression, CNV are included in "co-dependent genes" estimation. 

> The DepMap portal website (https://depmap.org/portal) provides a range of information for each gene, cell lines and lineage dependent on the gene, and co-dependent genes (i.e., other genes whose dependency scores are highly correlated with the gene) as well as basal transcriptome, copy numbers, and mutations of the gene. 

Thanks. 
Shicheng

**Comment by lgatto** [comment]
Please refer to the depmap portal help forum for questions relating to their data and only use this repository for questions related to the Bioconductor package.
