### ISSUE TITLE
Depmap Linux download without GUI

### ISSUE THREAD

**Issue by Shicheng-Guo** [UCLouvain-CBIO/depmap#68]
Hi Sir/Madam, 

Is there anyway to download depmap from Linux terminal? I want to download the data from linux server which don't have GUI and therefore, I cannot click the download button. 

https://ndownloader.figshare.com/files/27902091

Thanks. 

Shicheng

**Comment by lgatto** [comment]
You can access data from the `depmap` package in R. The original data sources are available on the depmap portal.
