### ISSUE TITLE
21Q3

### ISSUE THREAD

**Issue by allisonvuong** [UCLouvain-CBIO/depmap#69]
Hi @lgatto , @tfkillian , is 21_Q3 coming any time soon? :D 
FYI this has been a huge help for my organization.

Also FYI although we have experimented with the MAE, our visualization applications currently support SEs, so we concatenated multiple different molecular assays into a single SE assay, where each row corresponds to a single feature of a single molecular assay.

**Comment by tfkillian** [comment]
@allisonvuong You can track all current Broad Institute Depmap releases here: https://depmap.org/portal/download/ As you can see, 21Q3 is not yet available. Furthermore, it takes roughly a week upload the datasets to ExperimentHub and have them validated by the Bioconductor team. I am currently working on a MAE with all of the important datasets to be pushed with the next release, but feel free to send a pull request with code displaying how to build your MAE or SE.

**Comment by allisonvuong** [comment]
Thanks for the explanation @tfkillian. I see you started a PR here: https://github.com/UCLouvain-CBIO/depmap/pull/70. Would you like me to make the PR off the 21q3 branch?

**Comment by tfkillian** [comment]
@allisonvuong, I have pushed 21Q3 branch because 21Q3 data is now available on `ExperimentHub`. We are now just waiting for @lgatto to merge the branch and push to Bioconductor. If you have any changes that you'd like to make (e.g. accessor functions for a Depmap `MultiAssayExperiment` and how to build that object) , feel free to fork the 21Q3 branch.

**Comment by lgatto** [comment]
The latest version 1.7.1 is now available from github and will also be (in 24 hours or so) from Bioc (devel). 

Note that the package version in the original PR wasn't correct, so make sure you install the latest to avoid any confusion in the future.

**Comment by lgatto** [comment]
@allisonvuong regarding using SEs for the depmap data, there's also now the `Bioplex::ccleProteome2SummarizedExperiment()` that can be used to convert the proteomics data (see an example [here](https://ccb-hms.github.io/BioPlex/articles/BioPlex.html#proteome-data-1)).
