### ISSUE TITLE
Consider adding "essential" gene designations data

### ISSUE THREAD

**Issue by j-andrews7** [UCLouvain-CBIO/depmap#75]
The `CRISPR_common_essentials.csv` list is very helpful for CRISPR dependency screens to remove pan-lethal hits. Inclusion of this list in future releases would be very welcome and a relatively simple addition.

**Comment by lgatto** [comment]
Thank you for the suggestion!

**Comment by j-andrews7** [comment]
A closer look at this revealed that the essentiality data shown on the site is actually not available from the download page and only available through the hidden API (https://depmap.org/portal/api/download/gene_dep_summary). 

This is pretty frustrating, as I have not been able to determine how to pull it down for specific releases, only for the most recent one.

**Comment by j-andrews7** [comment]
I feel just providing it on its own and letting end-users determine how to filter the other files as necessary is likely sufficient. The API link above only pulls data for the latest release, more details can be found in [this depmap forum thread](https://forum.depmap.org/t/getting-dependent-cell-line-list-of-strongly-selective-genes-from-depmap-crispr-achilles/1173/5).

**Comment by tfkillian** [comment]
A new essential gene dataset has been made available. This dataset has been given the designation `gene_summary_22Q1` and has the EH number `EH7529` and can also be downloaded using its own accessor function, `depmap_gene_summary()`.

**Comment by j-andrews7** [comment]
This function has the same issue as #79 did. 

```
3: download failed
  hub path: ‘https://experimenthub.bioconductor.org/fetch/7579’
  cache resource: ‘EH7529 : 7579’
```

**Comment by tfkillian** [comment]
@j-andrews7 i will sort this out with the EH team.

**Comment by tfkillian** [comment]
@j-andrews7 I am able to successfully access `gene_summary_22Q1` both selecting this dataset by the EH number 7529 and by using the `depmap_gene_summary` function. What version of R and Bioconductor are you using?

**Comment by j-andrews7** [comment]
Tried again and it worked. 🤷‍♂️ 

Thanks for taking a look.
