### ISSUE TITLE
`depmap_drug_sensitivity()` throwing a 404

### ISSUE THREAD

**Issue by j-andrews7** [UCLouvain-CBIO/depmap#79]
Seems this data was removed?

```
depmap::depmap_drug_sensitivity()
snapshotDate(): 2022-04-26
see ?depmap and browseVignettes('depmap') for documentation
downloading 1 resources
retrieving 1 resource
  |=============================================================================================================| 100%

Error: failed to load resource
  name: EH7530
  title: drug_sensitivity_21Q2
  reason: 1 resources failed to download
In addition: Warning messages:
1: download failed
  web resource path: ‘https://experimenthub.bioconductor.org/fetch/7580’
  local file path: ‘C:\Users\jandrews\AppData\Local/R/cache/R/ExperimentHub/589c4ad59f5_7580’
  reason: Not Found (HTTP 404). 
2: bfcadd() failed; resource removed
  rid: BFC33
  fpath: ‘https://experimenthub.bioconductor.org/fetch/7580’
  reason: download failed 
3: download failed
  hub path: ‘https://experimenthub.bioconductor.org/fetch/7580’
  cache resource: ‘EH7530 : 7580’
  reason: bfcadd() failed; see warnings() 
```

**Comment by j-andrews7** [comment]
Seems a mismatch between the EHub ID that's provided to fetch (7580) and the actual one(7530). I assume this is on the EH/data upload side somewhere, as trying to fetch with ExperimentHub directly throws the same error (`eh[[7530]]`).

**Comment by tfkillian** [comment]
@j-andrews7 I also observe this error. This may be do to a miscommunication with the EH staff that this dataset was an update of an earlier release. I will resubmit this dataset to EH with the name `depmap_drug_sensitivity_22Q1` which should solve the issue.

**Comment by lshep** [comment]
drug_sensativity_21Q2.rda  was uploaded while the metadata provided is drug_sensitivity_21Q2. So there is a name mismatch.  Working with @tfkillian to have it resolved.

**Comment by tfkillian** [comment]
@lshep The original metadata that I submitted or this release has `drug_sensitivity_21Q2` in all instances: https://github.com/UCLouvain-CBIO/depmap/blob/master/inst/extdata/metadata_22Q1.csv I have re-uploaded the file with the name drug_sensitivity_21Q2.rda via azcopy. If this fixes the issue, please delete all EH references to `drug_sensitivity_22Q1`.

**Comment by lshep** [comment]
This should be resolved.  Please try downloading again
