### ISSUE TITLE
2022 Version Problem

### ISSUE THREAD

**Issue by omaaribra** [UCLouvain-CBIO/depmap#82]
Hello-
I used biocomanger to install the tool. But the version installed is depmap: 1.6.0 and ExperimentHub: 2.0.0. Any help on how to install the 2022 dataset?

Thanks!

**Comment by tfkillian** [comment]
@omaaribra you need to update to the most recent version of R = 4.2.1 and then update Bioconductor to 3.15. Then you should be able to access the 22Q1 versions of the datasets.

''' BiocManager::install(version = "3.15")
'''
