### ISSUE TITLE
depmap_copyNumber() function does not return CN data; returns metadata table

### ISSUE THREAD

**Issue by mfper** [UCLouvain-CBIO/depmap#83]
Hi,

I just wanted to bring this to your attention; in the vignette it says:

The most recent copyNumber dataset can be automatically loaded into R by using the depmap_copyNumber function.

But it just returns a metadata table. The output is formaly identical to depmap_metadata.

This can even be seen in the vignette output for depmap_copyNumber()

Thanks a lot for the very useful package,

MFP

**Comment by tfkillian** [comment]
@mfper, the depmap_copyNumber function is working fine for me, so I can't replicate this error. Can you let me know what version of R and Bioconductor you are using? I suggest updating R to the latest dev version. If this fails to resolve the error, please use the following code to access the most recent version of the copyNumber dataset:

'''
copyNumber <- eh[["EH7555"]]
'''

**Comment by mfper** [comment]
Hi tfkillian,

Following the vignette I had previously manageed to get the CNs with the code that you pasted in your reply.

In fact, now when I try it, depmap_copyNumber() works. 

I recently updated to R v4.2.2 so I suppose that's why. 

Unfortunately I am not sure which version I was using before the update.

Kind regards,

MFP
