### ISSUE TITLE
installation of package ‘depmap’ had non-zero exit status

### ISSUE THREAD

**Issue by Mango1235** [UCLouvain-CBIO/depmap#88]
if(!"depmap" %in% installed.packages()) BiocManager::install("depmap")
remotes::install_github("UCLouvain-CBIO/depmap", ref = "4a9f52ed6cf9c3821891ebdd9db317194d6518c9")
BiocManager::install("depmap",version = "3.17")

these three methods didn't work.

'getOption("repos")' replaces Bioconductor standard
repositories, see 'help("repositories", package =
"BiocManager")' for details.
Replacement repositories:
    CRAN: https://mirrors.tuna.tsinghua.edu.cn/CRAN/
Bioconductor version 3.17 (BiocManager 1.30.22), R
  4.3.1 (2023-06-16 ucrt)
Installing package(s) 'depmap'
installing the source package ‘depmap’

trying URL 'https://bioconductor.org/packages/3.17/data/experiment/src/contrib/depmap_1.14.0.tar.gz'
Content type 'application/x-gzip' length 1379521 bytes (1.3 MB)
downloaded 1.3 MB

* installing *source* package 'depmap' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Cannot connect to ExperimentHub server, using 'localHub=TRUE' instead
Using 'localHub=TRUE'
  If offline, please also see BiocManager vignette section on offline use
Error: package or namespace load failed for 'depmap':
 .onLoad failed in loadNamespace() for 'depmap', details:
  call: h(simpleError(msg, call))
  error: error in evaluating the argument 'x' in selecting a method for function 'query': Invalid Cache: sqlite file
  Hub has not been added to cache
  Run again with 'localHub=FALSE'
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'D:/00000/R4.3.1/R-4.3.1/library/depmap'

The downloaded source packages are in
	‘C:\Users\M\AppData\Local\Temp\RtmpaeE4pj\downloaded_packages’
Warning message:
In install.packages(...) :
  installation of package ‘depmap’ had non-zero exit status

**Comment by lgatto** [comment]
This could be linked to network issues - you were able to download the package, but then, can't access ExperimentHub (that hosts the data).

Could you try again.  The following is enough

```
BiocManager::install("depamap")
```

**Comment by Mango1235** [comment]
Thanks for your suggestion. I tried several times, but failed with the same error. It's weird, because I could install other bio-conductor packages using the same method, and the same network. I tried to install locally in R Studio, but it didn't work as well. Maybe I need a better network environment, or any other suggestions? Thanks!

install.packages("D:/CRISPR_in_R/depmap_1.14.0.tar.gz", repos = NULL, type = "source")
* installing *source* package 'depmap' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Cannot connect to ExperimentHub server, using 'localHub=TRUE' instead
Using 'localHub=TRUE'
  If offline, please also see BiocManager vignette section on offline use
Error: package or namespace load failed for 'depmap':
 .onLoad failed in loadNamespace() for 'depmap', details:
  call: h(simpleError(msg, call))
  error: error in evaluating the argument 'x' in selecting a method for function 'query': Invalid Cache: sqlite file
  Hub has not been added to cache
  Run again with 'localHub=FALSE'
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'D:/00000/R4.3.1/R-4.3.1/library/depmap'
Warning in install.packages :
  installation of package ‘D:/CRISPR_in_R/depmap_1.14.0.tar.gz’ had non-zero exit status

**Comment by lgatto** [comment]
Could you try to delete the ExperimentHub cache. You can find it with `tools::R_user_dir("ExperimentHub")`

**Comment by homerzpq** [comment]
I am also meeting the same problem when i install depmap. It can not connect to Experimenthub server. I could not  use Experimenthub directly. But when I run this code:
proxy <- httr::use_proxy(Sys.getenv('http_proxy'))
httr::set_config(proxy)
ExperimentHub::setExperimentHubOption("PROXY", proxy)
this could make Experimenthub work, but R still not able to install depmap.
Have you solved the problem?

**Comment by lgatto** [comment]
What I think happens is that the installation fails because the http proxy isn't set when installing depmap. Could you try to set these options in your `.Rprofile`.

**Comment by homerzpq** [comment]
It's done when I followed your advice! Thanks

**Comment by Mango1235** [comment]
Sorry for late reply. I tried the same method, but still failed to install the "depmap" package. Could you please share the code with me. Thanks!

**Comment by Mango1235** [comment]
Sorry for late reply. I tried the same method, but still failed to install the "depmap" package. Could you please share the code with me. Thanks! @homerzpq
