### ISSUE TITLE
Hub has not been added to cache

### ISSUE THREAD

**Issue by Mango1235** [UCLouvain-CBIO/depmap#89]
eh = ExperimentHub(localHub=TRUE)
Using 'localHub=TRUE'
  If offline, please also see BiocManager vignette section on offline use
using temporary cache C:\Users\M\AppData\Local\Temp\RtmpeSrYma/BiocFileCache
Error in .updateHubDB(hub_bfc, .class, url, proxy, localHub) : 
  Invalid Cache: sqlite file
  Hub has not been added to cache
  Run again with 'localHub=FALSE'

**Comment by lgatto** [comment]
Please provide some additional information/details when opening and issue.
