### ISSUE TITLE
cannot download

### ISSUE THREAD

**Issue by mkudelka** [UCLouvain-CBIO/depmap#90]
How do I download? I get the following error when downloading with BiocManager::install("depmap") & a similar error if I download from GitHub directly with BiocManager::install("uclouvain-cbio/depmap"):
```
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Bioconductor version 3.17 (BiocManager 1.30.22), R 4.3.2 (2023-10-31)
Installing package(s) 'depmap'
Warning: unable to access index for repository https://bioconductor.org/packages/3.17/bioc/bin/macosx/big-sur-arm64/contrib/4.3:
  cannot open URL 'https://bioconductor.org/packages/3.17/bioc/bin/macosx/big-sur-arm64/contrib/4.3/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.17/data/annotation/bin/macosx/big-sur-arm64/contrib/4.3:
  cannot open URL 'https://bioconductor.org/packages/3.17/data/annotation/bin/macosx/big-sur-arm64/contrib/4.3/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.17/data/experiment/bin/macosx/big-sur-arm64/contrib/4.3:
  cannot open URL 'https://bioconductor.org/packages/3.17/data/experiment/bin/macosx/big-sur-arm64/contrib/4.3/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.17/workflows/bin/macosx/big-sur-arm64/contrib/4.3:
  cannot open URL 'https://bioconductor.org/packages/3.17/workflows/bin/macosx/big-sur-arm64/contrib/4.3/PACKAGES'
installing the source package ‘depmap’

trying URL 'https://bioconductor.org/packages/3.17/data/experiment/src/contrib/depmap_1.14.0.tar.gz'
Content type 'application/gzip' length 1379521 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

* installing *source* package ‘depmap’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘depmap’:
 .onLoad failed in loadNamespace() for 'depmap', details:
  call: (function (cond) 
  error: error in evaluating the argument 'x' in selecting a method for function 'query': Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/depmap’

The downloaded source packages are in
	‘/private/var/folders/jt/3dy0tr091wq899wq92l544740000gn/T/RtmpiR64gI/downloaded_packages’
Warning message:
In install.packages(...) :
  installation of package ‘depmap’ had non-zero exit status
```

**Comment by lgatto** [comment]
Please update to Bioconductor 3.18 with to get the current version

```r
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.18")
```

then try installing the package again with

```r
BiocManager::install("depmap")
```

**Comment by mkudelka** [comment]
That worked - thanks!

**Comment by YanlanSun** [comment]
when Bioconductor version 3.18, the problem still occurs, how I can do to solve this problem? Thank you very much!

BiocManager::install("depmap")
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://mirrors.tuna.tsinghua.edu.cn/CRAN/
Bioconductor version 3.18 (BiocManager 1.30.22), R 4.3.2 (2023-10-31 ucrt)
Installing package(s) 'depmap'
安装源码包‘depmap’

试开URL’https://bioconductor.org/packages/3.18/data/experiment/src/contrib/depmap_1.16.0.tar.gz'
Content type 'application/x-gzip' length 1409559 bytes (1.3 MB)
downloaded 1.3 MB

* installing *source* package 'depmap' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Cannot connect to ExperimentHub server, using 'localHub=TRUE' instead
Using 'localHub=TRUE'
  If offline, please also see BiocManager vignette section on offline use
Error: package or namespace load failed for 'depmap':
 .onLoad failed in loadNamespace() for 'depmap', details:
  call: h(simpleError(msg, call))
  error: error in evaluating the argument 'x' in selecting a method for function 'query': Invalid Cache: sqlite file
  Hub has not been added to cache
  Run again with 'localHub=FALSE'
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'D:/R/R-4.3.2/library/depmap'

下载的程序包在
	‘C:\Users\18817\AppData\Local\Temp\RtmpkBpBQZ\downloaded_packages’里
Warning message:
In install.packages(...) : 安装程序包‘depmap’时退出狀態的值不是0

**Comment by lgatto** [comment]
Have you tried following the instructions in the message?
